[project]
name = "colonia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    # Using a specific tag
    "rupy-api @ git+https://github.com/manoelhc/rupy.git@v0.1.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
